language: cpp

compiler:
  - clang
  - gcc

script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - cmake --build . --config Debug -- -j $(nproc)
  - ctest -j $(nproc) --output-on-failure